# Generated by Django 3.1.7 on 2021-04-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20210412_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/worker/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('active', 'Анкета активна'), ('no_active', 'Анкета не активна')], default='no_active', max_length=50, verbose_name='Статус'),
        ),
    ]
