# Generated by Django 3.1.7 on 2021-04-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_auto_20210414_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='experience',
            field=models.DateField(null=True, verbose_name='Стаж'),
        ),
    ]
