# Generated by Django 3.1.7 on 2021-04-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_worker_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='price',
            field=models.CharField(default=19081997, max_length=50, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
