# Generated by Django 3.1.7 on 2021-04-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_worker_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='caption_price',
            field=models.CharField(choices=[('1', 'шт.'), ('2', 'услуга'), ('3', '60 минут'), ('4', 'по договорённости')], max_length=50, null=True, verbose_name='Подпись к цене'),
        ),
        migrations.AddField(
            model_name='worker',
            name='currency',
            field=models.CharField(choices=[('RUB', 'руб'), ('UAH', 'грн'), ('KZT', 'тенге')], max_length=50, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='experience',
            field=models.DateField(help_text='укажите с какого года вы работаете, ожидаемый формат "01.01.2010"', null=True, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
